/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoesRouteImport } from './routes/shoes'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as ElectronicsRouteImport } from './routes/electronics'
import { Route as BeautyRouteImport } from './routes/beauty'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const ShoesRoute = ShoesRouteImport.update({
  id: '/shoes',
  path: '/shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectronicsRoute = ElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyRoute = BeautyRouteImport.update({
  id: '/beauty',
  path: '/beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/beauty': typeof BeautyRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/health': typeof HealthRoute
  '/search': typeof SearchRoute
  '/shoes': typeof ShoesRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/beauty': typeof BeautyRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/health': typeof HealthRoute
  '/search': typeof SearchRoute
  '/shoes': typeof ShoesRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/beauty': typeof BeautyRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/health': typeof HealthRoute
  '/search': typeof SearchRoute
  '/shoes': typeof ShoesRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/beauty'
    | '/electronics'
    | '/fashion'
    | '/health'
    | '/search'
    | '/shoes'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/beauty'
    | '/electronics'
    | '/fashion'
    | '/health'
    | '/search'
    | '/shoes'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/beauty'
    | '/electronics'
    | '/fashion'
    | '/health'
    | '/search'
    | '/shoes'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BeautyRoute: typeof BeautyRoute
  ElectronicsRoute: typeof ElectronicsRoute
  FashionRoute: typeof FashionRoute
  HealthRoute: typeof HealthRoute
  SearchRoute: typeof SearchRoute
  ShoesRoute: typeof ShoesRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shoes': {
      id: '/shoes'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronics': {
      id: '/electronics'
      path: '/electronics'
      fullPath: '/electronics'
      preLoaderRoute: typeof ElectronicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty': {
      id: '/beauty'
      path: '/beauty'
      fullPath: '/beauty'
      preLoaderRoute: typeof BeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  BeautyRoute: BeautyRoute,
  ElectronicsRoute: ElectronicsRoute,
  FashionRoute: FashionRoute,
  HealthRoute: HealthRoute,
  SearchRoute: SearchRoute,
  ShoesRoute: ShoesRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
